//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketOffice.DateBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities : DbContext
    {
        public CinemaEntities()
            : base("name=CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinema> cinemas { get; set; }
        public virtual DbSet<Client> clients { get; set; }
        public virtual DbSet<Film> films { get; set; }
        public virtual DbSet<Reservation> reservations { get; set; }
        public virtual DbSet<Role> roles { get; set; }
        public virtual DbSet<Session> sessions { get; set; }
        public virtual DbSet<TypeSession> type_sessions { get; set; }
    }
}
