//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketOffice.DateBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities : DbContext
    {
        public CinemaEntities()
            : base("name=CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinema> Cinemas1 { get; set; }
        public virtual DbSet<Client> Clients1 { get; set; }
        public virtual DbSet<Role> Roles1 { get; set; }
        public virtual DbSet<Film> Films1 { get; set; }
        public virtual DbSet<TypeSession> TypeSessions { get; set; }
        public virtual DbSet<Reservation> Reservations1 { get; set; }
        public virtual DbSet<Session> Sessions1 { get; set; }
    }
}
