//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketOffice.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int reservation_id { get; set; }
        public int session_id { get; set; }
        public int client_id { get; set; }
        public int place { get; set; }
        public int row { get; set; }
        public int price { get; set; }
    
        public virtual Client client { get; set; }
        public virtual Session session { get; set; }
    }
}
