//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketOffice.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int role_id { get; set; }
        public string name { get; set; }
    
        public virtual Client clients { get; set; }
    }
}
