//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketOffice.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int cinema_id { get; set; }
        public int film_id { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public int type_session_id { get; set; }
    
        public virtual Cinema cinema { get; set; }
        public virtual Film film { get; set; }
        public virtual TypeSession type_sessions { get; set; }
    }
}
